# This pipeline builds all the containers in the repo.
# Each container is tagged and pushed wit the branch name
pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - export SANITIZED_BRANCH="$(echo $BITBUCKET_BRANCH | sed 's/\//_/g')"
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

          - docker build -t kasmweb/desktop:dev -t kasmweb/desktop-private:$SANITIZED_BRANCH  -f dockerfile-kasm-desktop .
          - docker build -t kasmweb/firefox:dev -t kasmweb/firefox-private:$SANITIZED_BRANCH -f dockerfile-kasm-firefox .
          - docker build -t kasmweb/chrome:dev -t kasmweb/chrome-private:$SANITIZED_BRANCH -f dockerfile-kasm-chrome .

          - docker push kasmweb/desktop-private:$SANITIZED_BRANCH
          - docker push kasmweb/firefox-private:$SANITIZED_BRANCH
          - docker push kasmweb/chrome-private:$SANITIZED_BRANCH

  branches:
    release/*:
      - step:
          services:
            - docker
          script:
            - export SANITIZED_BRANCH="$(echo $BITBUCKET_BRANCH | sed 's/\//_/g' | sed 's/release_//g')"
            - export SANITIZED_EDGE_BRANCH=${SANITIZED_BRANCH}-edge

            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

            - docker build -t kasmweb/desktop:dev -t kasmweb/desktop:$SANITIZED_BRANCH -t kasmweb/desktop:$SANITIZED_EDGE_BRANCH  -t kasmweb/desktop-private:$SANITIZED_BRANCH -t kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-desktop .
            - docker build -t kasmweb/firefox:dev -t kasmweb/firefox:$SANITIZED_BRANCH -t kasmweb/firefox:$SANITIZED_EDGE_BRANCH  -t kasmweb/firefox-private:$SANITIZED_BRANCH -t kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-firefox .
            - docker build -t kasmweb/chrome:dev -t kasmweb/chrome:$SANITIZED_BRANCH -t kasmweb/chrome:$SANITIZED_EDGE_BRANCH  -t kasmweb/chrome-private:$SANITIZED_BRANCH -t kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-chrome .

            - docker push kasmweb/desktop:$SANITIZED_BRANCH
            - docker push kasmweb/desktop:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/desktop-private:$SANITIZED_BRANCH
            - docker push kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/firefox:$SANITIZED_BRANCH
            - docker push kasmweb/firefox:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/firefox-private:$SANITIZED_BRANCH
            - docker push kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/chrome:$SANITIZED_BRANCH
            - docker push kasmweb/chrome:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/chrome-private:$SANITIZED_BRANCH
            - docker push kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH
    develop:
      - step:
          services:
            - docker
          script:
            - export SANITIZED_BRANCH="$(echo $BITBUCKET_BRANCH | sed 's/\//_/g' | sed 's/release_//g')"
            - export SANITIZED_EDGE_BRANCH=${SANITIZED_BRANCH}-edge

            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

            - docker build -t kasmweb/desktop:dev -t kasmweb/desktop:$SANITIZED_BRANCH -t kasmweb/desktop:$SANITIZED_EDGE_BRANCH  -t kasmweb/desktop-private:$SANITIZED_BRANCH -t kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-desktop .
            - docker build -t kasmweb/firefox:dev -t kasmweb/firefox:$SANITIZED_BRANCH -t kasmweb/firefox:$SANITIZED_EDGE_BRANCH  -t kasmweb/firefox-private:$SANITIZED_BRANCH -t kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-firefox .
            - docker build -t kasmweb/chrome:dev -t kasmweb/chrome:$SANITIZED_BRANCH -t kasmweb/chrome:$SANITIZED_EDGE_BRANCH  -t kasmweb/chrome-private:$SANITIZED_BRANCH -t kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-chrome .

            - docker push kasmweb/desktop:$SANITIZED_BRANCH
            - docker push kasmweb/desktop:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/desktop-private:$SANITIZED_BRANCH
            - docker push kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/firefox:$SANITIZED_BRANCH
            - docker push kasmweb/firefox:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/firefox-private:$SANITIZED_BRANCH
            - docker push kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/chrome:$SANITIZED_BRANCH
            - docker push kasmweb/chrome:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/chrome-private:$SANITIZED_BRANCH
            - docker push kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH
  custom:
    edge-updates:
      - step:
          services:
            - docker
          script:
            - export SANITIZED_BRANCH="$(echo $BITBUCKET_BRANCH | sed 's/\//_/g' | sed 's/release_//g')"
            - export SANITIZED_EDGE_BRANCH=${SANITIZED_BRANCH}-edge

            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

            - sed -i "s/core:1.3.0/core-edge:1.3.0/g" dockerfile-kasm-desktop
            - sed -i "s/core:1.3.0/core-edge:1.3.0/g" dockerfile-kasm-firefox

            - docker build -t kasmweb/desktop:dev -t kasmweb/desktop:$SANITIZED_EDGE_BRANCH  -t kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-desktop .
            - docker build -t kasmweb/firefox:dev -t kasmweb/firefox:$SANITIZED_EDGE_BRANCH  -t kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-firefox .
            - docker build -t kasmweb/chrome:dev -t kasmweb/chrome:$SANITIZED_EDGE_BRANCH  -t kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH  -f dockerfile-kasm-chrome .

            - docker push kasmweb/desktop:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/desktop-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/firefox:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/firefox-private:$SANITIZED_EDGE_BRANCH

            - docker push kasmweb/chrome:$SANITIZED_EDGE_BRANCH
            - docker push kasmweb/chrome-private:$SANITIZED_EDGE_BRANCH
